#!/bin/bash

set +ex

docker-compose \
    run --rm --entrypoint premake5 \
    build \
    --cc=gcc gmake

docker-compose \
    run --rm --entrypoint make \
    build clean

docker-compose \
    run --rm --entrypoint make \
    build
